"use client";

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { fas, far, fal } from '@fortawesome/free-solid-svg-icons';

const Compte = () => {

    return(
        <>
            <FontAwesomeIcon icon={fas.faHouse} />
                <h2>Compte</h2>
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
        </>
    );
}

export default Compte;
