"use client";

const Compte = () => {

    return(
        <>
            <div className="compte">
                <h2>Compte</h2>
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
                reogjeogjgorjtrg
                ^gkgrpgjtrgotp 
                eg^ggprgkprogpgojgoprjtgogorijgrgijrogrjgiorjgogjgorjg
            </div>
        </>
    );
}

export default Compte;
